version: "3"

services:
  redisdb:
    image: redis:latest
    ports: 
      - 6379:6379

  mymongo:
    image: mongo:4.4
    ports: 
      - 27101:27017

  mysql:
    image: mysql:latest
    ports: 
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    volumes: 
      - "./sqlTables.sql:/docker-entrypoint-initdb.d/1-structure.sql"
  
  mongoPerfTest:
    image: mongo:4.4
    ports: 
      - 27701:27017
  
  redisPerfTest:
    image: redis:latest
    ports: 
      - 6364:6379
  
  mysqlPerfTest:
    image: mysql:latest
    ports: 
      - 3334:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysqlPerfTest
    volumes: 
      - "./sqlTablesPerf.sql:/docker-entrypoint-initdb.d/1-sqlTables.sql"
      