version: "3"

services:
  

  mongo:
    image: mongo:latest
    ports: 
      - 27100:27017

  mongo-seed:
    image: mongo:latest
    links:
        - mongo
    volumes:
        - ./mongo-seed:/mongo-seed
    command:
        /mongo-seed/import.sh

  mysql:
    image: mysql:latest
    ports: 
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=INVENTORY
    volumes: 
      - "./mysql/data.sql:/docker-entrypoint-initdb.d/data.sql"
