version: "3"

services:
  redisdb:
    image: redis:latest
    volumes :
      - "./src/main/resources/imdb/:/data/"
    ports: 
      - 6379:6379
      
  mymongo:
    image: mongo:latest
    ports: 
      - 27100:27017
    environment: 
      - MONGO_INITDB_DATABASE=mymongo

  mysql:
    image: mysql:latest
    ports: 
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
